Exclude an older coroutines version from getting copied as a dependency
Having both 1.9.0 and 1.11.0 in the classpath causes a `java.lang.NoSuchMethodError` running the screenshot scripts